// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/materials": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/materials";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./home/Home.tsx": {
    id: "home/Home";
    page: "/home";
  };
  "./routes/Materials.tsx": {
    id: "routes/Materials";
    page: "/materials";
  };
};