// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/useapp": {
    params: {};
  };
  "/create-prompt": {
    params: {};
  };
  "/materials": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/privacypolicy": {
    params: {};
  };
  "/termsandservice": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/login" | "/help" | "/useapp" | "/create-prompt" | "/materials" | "/signup" | "/privacypolicy" | "/termsandservice" | "/gallery";
  };
  "routes/welcomepage.tsx": {
    id: "routes/welcomepage";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "routes/useapp.tsx": {
    id: "routes/useapp";
    page: "/useapp";
  };
  "routes/create-prompt.tsx": {
    id: "routes/create-prompt";
    page: "/create-prompt";
  };
  "routes/materials.tsx": {
    id: "routes/materials";
    page: "/materials";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/privacypolicy.tsx": {
    id: "routes/privacypolicy";
    page: "/privacypolicy";
  };
  "routes/termsandservice.tsx": {
    id: "routes/termsandservice";
    page: "/termsandservice";
  };
  "routes/gallery.tsx": {
    id: "routes/gallery";
    page: "/gallery";
  };
};